//Try - catch
/*const hello = ()=> {
    console.log('Hello')
}*/

try {
    hello();

}

/* Error default
catch (error) {
    console.log(error);
}
*/

//Error personalizado
catch {
    console.log('Algo paso')
}